#!/bin/bash

# ============================================
# FILE COLLECTOR FOR MARKETING MODULE V2
# Updated: Includes Discover Pages & New Components
# ============================================
#
# Changes from v1:
# - Added: Discover pages (page.tsx, client.tsx, [category])
# - Added: About page
# - Added: New platform-landing components (discover-header, discover-hero, etc)
# - Added: tenant-preview-drawer.tsx
# - UI Components: Only list filenames (auto-generated by shadcn/ui CLI)
#
# Usage:
# chmod +x collect-marketing-module-v2.sh
# ./collect-marketing-module-v2.sh
#
# Run from: /path/to/client (root folder Next.js)
#
# ============================================

# ============================================
# SETUP OUTPUT DIRECTORY & FILE
# ============================================

OUTPUT_DIR="collections"
OUTPUT_FILE="$OUTPUT_DIR/marketing-module-v2-$(date +%Y%m%d-%H%M%S).txt"

# Create collections directory if not exists
if [ ! -d "$OUTPUT_DIR" ]; then
    echo "📁 Creating collections directory..."
    mkdir -p "$OUTPUT_DIR"
fi

echo "🚀 Marketing Module Collector - V2 (with Discover)"
echo "=============================================="
echo ""
echo "📍 Working directory: $(pwd)"
echo "📁 Output directory: $OUTPUT_DIR/"
echo "📄 Output file: $OUTPUT_FILE"
echo ""

# Initialize counters
FOUND_COUNT=0
NOT_FOUND_COUNT=0
TOTAL_LINES=0
UI_COUNT=0

# Start file
cat > "$OUTPUT_FILE" << EOF
================================================================
MARKETING MODULE V2 - COMPLETE DEPENDENCIES
Generated on: $(date)
Working Directory: $(pwd)
================================================================

INCLUDES:
- Marketing Pages (home, fitur, cara-kerja, harga, about)
- Discover Pages (discover, discover/[category])
- Platform Landing Components (27 files)
- UI Components (shadcn/ui): Listed by name only
- SEO, Lib, Providers, Config

================================================================

EOF

# ============================================
# FUNCTION: Collect Full File
# ============================================

collect_file() {
    local file=$1
    local relative_path=$2
    
    if [ -f "$file" ]; then
        local line_count=$(wc -l < "$file")
        TOTAL_LINES=$((TOTAL_LINES + line_count))
        FOUND_COUNT=$((FOUND_COUNT + 1))
        echo "✅ Found: $relative_path (${line_count} lines)"
        cat >> "$OUTPUT_FILE" << EOF

================================================
FILE: $relative_path
Lines: $line_count
================================================

$(cat "$file")

EOF
    else
        NOT_FOUND_COUNT=$((NOT_FOUND_COUNT + 1))
        echo "❌ NOT FOUND: $relative_path"
        cat >> "$OUTPUT_FILE" << EOF

================================================
FILE: $relative_path
Lines: 0
================================================

⚠️ FILE NOT FOUND - Needs to be created!

EOF
    fi
}

# ============================================
# FUNCTION: List UI Component (Name Only)
# ============================================

list_ui_component() {
    local file=$1
    local relative_path=$2
    
    if [ -f "$file" ]; then
        UI_COUNT=$((UI_COUNT + 1))
        echo "📦 Listed: $relative_path (shadcn/ui)"
    else
        echo "❌ NOT FOUND: $relative_path (shadcn/ui)"
    fi
}

# ============================================
# SECTION 1: MARKETING PAGES (5 files)
# ============================================

echo ""
echo "═══════════════════════════════════════════"
echo "🎯 MARKETING PAGES (5 files)"
echo "═══════════════════════════════════════════"
echo ""

collect_file "src/app/page.tsx" "src/app/page.tsx"
collect_file "src/app/about/page.tsx" "src/app/about/page.tsx"
collect_file "src/app/fitur/page.tsx" "src/app/fitur/page.tsx"
collect_file "src/app/cara-kerja/page.tsx" "src/app/cara-kerja/page.tsx"
collect_file "src/app/harga/page.tsx" "src/app/harga/page.tsx"

# ============================================
# SECTION 2: DISCOVER PAGES (6 files) - NEW!
# ============================================

echo ""
echo "═══════════════════════════════════════════"
echo "🔍 DISCOVER PAGES (6 files) - NEW!"
echo "═══════════════════════════════════════════"
echo ""

collect_file "src/app/discover/page.tsx" "src/app/discover/page.tsx"
collect_file "src/app/discover/client.tsx" "src/app/discover/client.tsx"
collect_file "src/app/discover/[category]/page.tsx" "src/app/discover/[category]/page.tsx"
collect_file "src/app/discover/[category]/client.tsx" "src/app/discover/[category]/client.tsx"
collect_file "src/app/discover/[category]/not-found.tsx" "src/app/discover/[category]/not-found.tsx"

# ============================================
# SECTION 3: PLATFORM LANDING COMPONENTS (27 files)
# ============================================

echo ""
echo "═══════════════════════════════════════════"
echo "🔴 PLATFORM LANDING COMPONENTS (27 files)"
echo "═══════════════════════════════════════════"
echo ""

# Index & Layout
collect_file "src/components/platform-landing/index.ts" "src/components/platform-landing/index.ts"

# Header & Footer
collect_file "src/components/platform-landing/landing-header.tsx" "src/components/platform-landing/landing-header.tsx"
collect_file "src/components/platform-landing/landing-footer.tsx" "src/components/platform-landing/landing-footer.tsx"
collect_file "src/components/platform-landing/minimal-footer.tsx" "src/components/platform-landing/minimal-footer.tsx"

# Discover Components (NEW)
echo ""
echo "🔥 DISCOVER COMPONENTS (NEW):"
collect_file "src/components/platform-landing/discover-header.tsx" "src/components/platform-landing/discover-header.tsx"
collect_file "src/components/platform-landing/discover-hero.tsx" "src/components/platform-landing/discover-hero.tsx"
collect_file "src/components/platform-landing/category-filter-bar.tsx" "src/components/platform-landing/category-filter-bar.tsx"
collect_file "src/components/platform-landing/tenant-preview-drawer.tsx" "src/components/platform-landing/tenant-preview-drawer.tsx"

# Hero & Intro Sections
echo ""
echo "📦 HERO & INTRO SECTIONS:"
collect_file "src/components/platform-landing/hero-section.tsx" "src/components/platform-landing/hero-section.tsx"
collect_file "src/components/platform-landing/logos-section.tsx" "src/components/platform-landing/logos-section.tsx"
collect_file "src/components/platform-landing/problem-section.tsx" "src/components/platform-landing/problem-section.tsx"
collect_file "src/components/platform-landing/solution-section.tsx" "src/components/platform-landing/solution-section.tsx"
collect_file "src/components/platform-landing/honest-section.tsx" "src/components/platform-landing/honest-section.tsx"
collect_file "src/components/platform-landing/target-user-section.tsx" "src/components/platform-landing/target-user-section.tsx"

# Feature Sections
echo ""
echo "📦 FEATURE SECTIONS:"
collect_file "src/components/platform-landing/how-it-works-section.tsx" "src/components/platform-landing/how-it-works-section.tsx"
collect_file "src/components/platform-landing/features-section.tsx" "src/components/platform-landing/features-section.tsx"
collect_file "src/components/platform-landing/fibidy-ai-section.tsx" "src/components/platform-landing/fibidy-ai-section.tsx"
collect_file "src/components/platform-landing/categories-section.tsx" "src/components/platform-landing/categories-section.tsx"

# Testimonials
echo ""
echo "📦 TESTIMONIAL SECTIONS:"
collect_file "src/components/platform-landing/testimonial-highlight-section.tsx" "src/components/platform-landing/testimonial-highlight-section.tsx"
collect_file "src/components/platform-landing/testimonials-section.tsx" "src/components/platform-landing/testimonials-section.tsx"
collect_file "src/components/platform-landing/lazy-testimonials.tsx" "src/components/platform-landing/lazy-testimonials.tsx"

# Pricing & CTA
echo ""
echo "📦 PRICING & CTA:"
collect_file "src/components/platform-landing/pricing-section.tsx" "src/components/platform-landing/pricing-section.tsx"
collect_file "src/components/platform-landing/faq-section.tsx" "src/components/platform-landing/faq-section.tsx"
collect_file "src/components/platform-landing/cta-section.tsx" "src/components/platform-landing/cta-section.tsx"

# UMKM Showcase
echo ""
echo "📦 UMKM SHOWCASE:"
collect_file "src/components/platform-landing/umkm-discover-section.tsx" "src/components/platform-landing/umkm-discover-section.tsx"
collect_file "src/components/platform-landing/umkm-showcase-section.tsx" "src/components/platform-landing/umkm-showcase-section.tsx"

# Blog (if exists)
echo ""
echo "📦 BLOG (Optional):"
collect_file "src/components/platform-landing/blog-section.tsx" "src/components/platform-landing/blog-section.tsx"

# ============================================
# SECTION 4: UI COMPONENTS (shadcn/ui)
# ✅ LIST ONLY - No Full Content
# ============================================

echo ""
echo "═══════════════════════════════════════════"
echo "🟠 UI COMPONENTS - shadcn/ui (20 files)"
echo "   ℹ️  Auto-generated by CLI - Listed only"
echo "═══════════════════════════════════════════"
echo ""

cat >> "$OUTPUT_FILE" << EOF

================================================
UI COMPONENTS (shadcn/ui) - Auto-generated
================================================

These components are auto-generated by shadcn/ui CLI.
No need to include full content - just verify they exist.

Required UI Components:

EOF

# Core UI
list_ui_component "src/components/ui/button.tsx" "src/components/ui/button.tsx"
list_ui_component "src/components/ui/badge.tsx" "src/components/ui/badge.tsx"
list_ui_component "src/components/ui/card.tsx" "src/components/ui/card.tsx"
list_ui_component "src/components/ui/avatar.tsx" "src/components/ui/avatar.tsx"
list_ui_component "src/components/ui/input.tsx" "src/components/ui/input.tsx"
list_ui_component "src/components/ui/skeleton.tsx" "src/components/ui/skeleton.tsx"

# Navigation
list_ui_component "src/components/ui/accordion.tsx" "src/components/ui/accordion.tsx"
list_ui_component "src/components/ui/sheet.tsx" "src/components/ui/sheet.tsx"
list_ui_component "src/components/ui/navigation-menu.tsx" "src/components/ui/navigation-menu.tsx"
list_ui_component "src/components/ui/dropdown-menu.tsx" "src/components/ui/dropdown-menu.tsx"
list_ui_component "src/components/ui/tabs.tsx" "src/components/ui/tabs.tsx"

# Drawer (for tenant preview)
list_ui_component "src/components/ui/drawer.tsx" "src/components/ui/drawer.tsx"
list_ui_component "src/components/ui/dialog.tsx" "src/components/ui/dialog.tsx"
list_ui_component "src/components/ui/scroll-area.tsx" "src/components/ui/scroll-area.tsx"

# Decorative
list_ui_component "src/components/ui/dot-pattern.tsx" "src/components/ui/dot-pattern.tsx"
list_ui_component "src/components/ui/word-rotate.tsx" "src/components/ui/word-rotate.tsx"
list_ui_component "src/components/ui/bento-grid.tsx" "src/components/ui/bento-grid.tsx"
list_ui_component "src/components/ui/highlighter.tsx" "src/components/ui/highlighter.tsx"
list_ui_component "src/components/ui/interactive-hover-button.tsx" "src/components/ui/interactive-hover-button.tsx"
list_ui_component "src/components/ui/marquee.tsx" "src/components/ui/marquee.tsx"

# Notification
list_ui_component "src/components/ui/sonner.tsx" "src/components/ui/sonner.tsx"

# Write UI component list to output
cat >> "$OUTPUT_FILE" << EOF
1. ✅ button.tsx
2. ✅ badge.tsx
3. ✅ card.tsx
4. ✅ avatar.tsx
5. ✅ input.tsx
6. ✅ skeleton.tsx
7. ✅ accordion.tsx
8. ✅ sheet.tsx
9. ✅ navigation-menu.tsx
10. ✅ dropdown-menu.tsx
11. ✅ tabs.tsx
12. ✅ drawer.tsx
13. ✅ dialog.tsx
14. ✅ scroll-area.tsx
15. ✅ dot-pattern.tsx
16. ✅ word-rotate.tsx
17. ✅ bento-grid.tsx
18. ✅ highlighter.tsx
19. ✅ interactive-hover-button.tsx
20. ✅ marquee.tsx
21. ✅ sonner.tsx

Note: All UI components are auto-generated via:
  npx shadcn@latest add [component-name]

If any component is missing, regenerate with CLI.

================================================

EOF

# ============================================
# SECTION 5: SEO COMPONENTS
# ============================================

echo ""
echo "═══════════════════════════════════════════"
echo "🔍 SEO COMPONENTS (2 files)"
echo "═══════════════════════════════════════════"
echo ""

collect_file "src/components/seo/index.ts" "src/components/seo/index.ts"
collect_file "src/components/seo/organization-schema.tsx" "src/components/seo/organization-schema.tsx"

# ============================================
# SECTION 6: LIB UTILITIES
# ============================================

echo ""
echo "═══════════════════════════════════════════"
echo "🟡 LIB UTILITIES (6 files)"
echo "═══════════════════════════════════════════"
echo ""

collect_file "src/lib/cn.ts" "src/lib/cn.ts"
collect_file "src/lib/utils.ts" "src/lib/utils.ts"
collect_file "src/lib/format.ts" "src/lib/format.ts"
collect_file "src/lib/validations.ts" "src/lib/validations.ts"
collect_file "src/lib/seo.ts" "src/lib/seo.ts"
collect_file "src/lib/store-url.ts" "src/lib/store-url.ts"

# ============================================
# SECTION 7: STYLES & LAYOUT
# ============================================

echo ""
echo "═══════════════════════════════════════════"
echo "🎨 STYLES & LAYOUT (2 files)"
echo "═══════════════════════════════════════════"
echo ""

collect_file "src/app/globals.css" "src/app/globals.css"
collect_file "src/app/layout.tsx" "src/app/layout.tsx"

# ============================================
# SECTION 8: PROVIDERS
# ============================================

echo ""
echo "═══════════════════════════════════════════"
echo "🔌 PROVIDERS (4 files)"
echo "═══════════════════════════════════════════"
echo ""

collect_file "src/providers/index.tsx" "src/providers/index.tsx"
collect_file "src/providers/theme-provider.tsx" "src/providers/theme-provider.tsx"
collect_file "src/providers/hydration-provider.tsx" "src/providers/hydration-provider.tsx"
collect_file "src/providers/toast-provider.tsx" "src/providers/toast-provider.tsx"

# ============================================
# SECTION 9: CONFIG
# ============================================

echo ""
echo "═══════════════════════════════════════════"
echo "⚙️ CONFIG (5 files)"
echo "═══════════════════════════════════════════"
echo ""

collect_file "src/config/site.ts" "src/config/site.ts"
collect_file "src/config/constants.ts" "src/config/constants.ts"
collect_file "src/config/categories.ts" "src/config/categories.ts"
collect_file "src/config/seo.config.ts" "src/config/seo.config.ts"
collect_file "src/config/navigation.ts" "src/config/navigation.ts"

# ============================================
# SUMMARY
# ============================================

TOTAL_COLLECTED=$((FOUND_COUNT + NOT_FOUND_COUNT))
TOTAL_FILES=$((TOTAL_COLLECTED + UI_COUNT))

echo ""
echo "═══════════════════════════════════════════"
echo "📊 COLLECTION SUMMARY"
echo "═══════════════════════════════════════════"
echo ""

cat >> "$OUTPUT_FILE" << EOF

================================================================
COLLECTION SUMMARY
================================================================

📦 Custom Components (Full Content):
   ✅ Found: $FOUND_COUNT files
   ❌ Missing: $NOT_FOUND_COUNT files
   📝 Total lines: $TOTAL_LINES

🟠 UI Components (shadcn/ui - Listed Only):
   📋 Total: $UI_COUNT files
   ℹ️  Auto-generated by CLI

📊 Grand Total:
   🎯 Marketing Pages: 5
   🔍 Discover Pages: 5 (NEW)
   🔴 Platform Landing: 27
   🟠 UI Components: 21 (listed only)
   🔍 SEO: 2
   🟡 Lib: 6
   🎨 Styles: 2
   🔌 Providers: 4
   ⚙️ Config: 5
   ─────────────────
   📁 Total Files: $TOTAL_FILES

🎉 Collection Method:
   - Custom code: Full content collected
   - shadcn/ui: Names listed only (auto-generated)
   - File size optimized for readability

📍 Output Location:
   $(pwd)/$OUTPUT_FILE

================================================================
END OF COLLECTION
================================================================
EOF

echo ""
echo "✅ Collection complete!"
echo ""
echo "📁 Output directory: $OUTPUT_DIR/"
echo "📄 Output file: $OUTPUT_FILE"
echo "📊 File size: $(du -h "$OUTPUT_FILE" 2>/dev/null | cut -f1 || echo "N/A")"
echo ""
echo "📋 Summary:"
echo "   ✅ Custom files found: $FOUND_COUNT"
echo "   ❌ Missing: $NOT_FOUND_COUNT"
echo "   📦 UI components: $UI_COUNT (listed only)"
echo "   📝 Total lines collected: $TOTAL_LINES"
echo "   📁 Total files tracked: $TOTAL_FILES"
echo ""
if [ $NOT_FOUND_COUNT -eq 0 ]; then
    echo "🎉 All files collected successfully!"
else
    echo "⚠️  WARNING: $NOT_FOUND_COUNT file(s) missing - check output file"
fi
echo ""
echo "📂 Navigate to output:"
echo "   cd $OUTPUT_DIR"
echo "   cat $(basename $OUTPUT_FILE)"
echo ""
echo "🎉 Done!"